swipe:
  3:
    left:
        sendkey: "LEFTALT+RIGHT" # History forward
    right:
        sendkey: "LEFTALT+LEFT" # History back
    up:
        sendkey: "LEFTCTRL+T" # new tab
    down:
        sendkey: "LEFTCTRL+W" # close tab
  4:
    left:
        sendkey: "LEFTMETA+LEFTCTRL+RIGHT" 
    right:
        sendkey: "LEFTMETA+LEFTCTRL+LEFT" 
    up:
        sendkey: "LEFTMETA+LEFTCTRL+DOWN" 
    down:
        sendkey: "LEFTMETA+LEFTCTRL+UP" 
pinch:
     in:
        sendkey: "LEFTCTRL+KPPLUS" # zoom in
     out:
        sendkey: "LEFTCTRL+KPMINUS" # zoom out

threshold:
  pinch: 0.5

interval:
  swipe: 0.75
  pinch: 0.5
